"""LLM-BreakBench analyzer.

Reads every results/*.json produced by runner.py and generates:
  * charts/pass_rate_by_prompt.png   - ablation effect per model
  * charts/pass_rate_by_category.png - which trap families break models
  * REPORT.md                        - tables + failure inventory to annotate

Usage:
    python analyze.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

RESULTS_DIR = Path("results")
CHARTS_DIR = Path("charts")
SUITE = Path("suites/traps.json")


def load_runs() -> list[dict]:
    runs = []
    for path in sorted(RESULTS_DIR.glob("*.json")):
        runs.append(json.loads(path.read_text(encoding="utf-8")))
    if not runs:
        raise SystemExit("No results found - run runner.py first.")
    return runs


def task_categories() -> dict[str, str]:
    suite = json.loads(SUITE.read_text(encoding="utf-8"))
    return {t["task_id"]: t["category"] for t in suite}


def chart_by_prompt(runs: list[dict]) -> None:
    models = sorted({r["model"] for r in runs})
    variants = sorted({r["prompt_variant"] for r in runs})
    fig, ax = plt.subplots(figsize=(9, 5))
    width = 0.8 / max(len(models), 1)
    for i, model in enumerate(models):
        rates = []
        for v in variants:
            match = [r for r in runs
                     if r["model"] == model and r["prompt_variant"] == v]
            rates.append(match[0]["summary"]["pass_rate"] * 100 if match else 0)
        xs = [j + i * width for j in range(len(variants))]
        bars = ax.bar(xs, rates, width=width, label=model)
        ax.bar_label(bars, fmt="%.0f%%", fontsize=8)
    ax.set_xticks([j + width * (len(models) - 1) / 2 for j in range(len(variants))])
    ax.set_xticklabels(variants)
    ax.set_ylabel("Pass rate (%)")
    ax.set_ylim(0, 105)
    ax.set_title("BreakBench pass rate by prompt variant")
    ax.legend()
    fig.tight_layout()
    fig.savefig(CHARTS_DIR / "pass_rate_by_prompt.png", dpi=150)
    plt.close(fig)


def chart_by_category(runs: list[dict]) -> None:
    cats = task_categories()
    # aggregate across all runs: category -> [passed, total]
    agg: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for run in runs:
        for res in run["results"]:
            cat = cats.get(res["task_id"], "other")
            agg[cat][1] += 1
            if res["passed"]:
                agg[cat][0] += 1
    names = sorted(agg, key=lambda c: agg[c][0] / agg[c][1])
    rates = [agg[c][0] / agg[c][1] * 100 for c in names]
    fig, ax = plt.subplots(figsize=(9, 5))
    bars = ax.barh(names, rates)
    ax.bar_label(bars, fmt="%.0f%%", fontsize=8)
    ax.set_xlabel("Pass rate (%) across all models and prompts")
    ax.set_xlim(0, 105)
    ax.set_title("Which trap categories break models most")
    fig.tight_layout()
    fig.savefig(CHARTS_DIR / "pass_rate_by_category.png", dpi=150)
    plt.close(fig)


def write_report(runs: list[dict]) -> None:
    cats = task_categories()
    lines = [
        "# LLM-BreakBench findings",
        "",
        "Adversarial evaluation of code-generation models on classic Python",
        "pitfalls, with a prompt-engineering ablation. Generated by `analyze.py`;",
        "commentary sections are then written by hand.",
        "",
        "## Ablation grid",
        "",
        "| Model | Prompt variant | Pass rate | Failure modes |",
        "|---|---|---|---|",
    ]
    for run in runs:
        s = run["summary"]
        modes = ", ".join(f"{k}:{v}" for k, v in s["failure_modes"].items()) or "-"
        lines.append(f"| {run['model']} | {run['prompt_variant']} "
                     f"| {s['passed']}/{s['tasks']} ({s['pass_rate']:.0%}) "
                     f"| {modes} |")
    lines += [
        "",
        "![Pass rate by prompt](charts/pass_rate_by_prompt.png)",
        "",
        "![Pass rate by category](charts/pass_rate_by_category.png)",
        "",
        "## Failure inventory",
        "",
    ]
    for run in runs:
        failures = [r for r in run["results"] if not r["passed"]]
        if not failures:
            continue
        lines.append(f"### {run['model']} / {run['prompt_variant']}")
        lines.append("")
        for res in failures:
            cat = cats.get(res["task_id"], "?")
            lines.append(f"- **{res['task_id']}** ({cat}) - "
                         f"`{res['failure_mode']}`, "
                         f"{res['tests_passed']}/{res['tests_total']} tests")
        lines.append("")
    lines += [
        "## Analysis (written by hand)",
        "",
        "_Which trap categories were hardest, did prompt engineering help,",
        "and what does this imply for training data design? Fill in after",
        "reviewing the charts and the error traces in results/*.json._",
        "",
    ]
    Path("REPORT.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    CHARTS_DIR.mkdir(exist_ok=True)
    runs = load_runs()
    chart_by_prompt(runs)
    chart_by_category(runs)
    write_report(runs)
    print(f"Charts written to {CHARTS_DIR}/, report to REPORT.md")


if __name__ == "__main__":
    main()
